### PR TITLE
#158422013  Add index login  and signup page

### PR DESCRIPTION
**Pull request by LarryKarani**
**What does this PR do?**

       - add a home page with links to the sign in and signup pages

**Description of Task to be completed**  

        - Building a User interface prototype with no functionality using only CSS and HTML

**How the app should be tested**

        - [](github.com/larryTheGeek/RideMyWay) download the repo or clone it

        - navigate into RideMyWay Folder
-open the index.html file with your browser
**Any background context you want to provide?**
         The UI homepage is slightly unresponsive
**What is the relevant pivotal tracker story**

        #158422013

cap2

cap3

capture

### CODE REVIEW

**Comment by TheSteelGuy** [comment]
wonderful UI design bro

**Comment by benlegendj** [comment]
Nice one buddy

**Comment by kwameasiago** [comment]
nice interface

**Comment by evamaina** [comment]
wonderful.Nice background color

**Pull request closed without merging**
